// Package Openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package Openapi

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Member defines model for Member.
type Member struct {
	CvUrl          string `json:"cvUrl"`
	GithubPicture  string `json:"githubPicture"`
	GithubUserName string `json:"githubUserName"`
	Id             int64  `json:"id"`
}

// WebService defines model for WebService.
type WebService struct {
	Description string `json:"description"`
	Id          int64  `json:"id"`
	Url         string `json:"url"`
}

