name: ci

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOST: ${{ secrets.DB_HOST }}
  TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
  TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
  TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker set up
        run: |
          cp .air.normal.conf .air.conf
          docker-compose up --build -d
      - name: Execute CI
        run: |
          sleep 5
          docker-compose exec -T ${DB_HOST} service mysql status
          docker-compose exec -T go make migrate-up
          docker-compose exec -T go make ci
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
#      - name: Send coverage
#        env:
#          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: goveralls -coverprofile=covprofile.out -service=github
